### PR TITLE
Introduce tox and TravisCI

### PR DESCRIPTION
**Pull request by meshy**
Hi there, I hope you're still accepting pull-requests!

This pull-request:

- Adds tox to run the tests against Django 1.8 through to Django 2.1, on Python 2 and 3.
- Adds a TravisCI config to avoid regressions (can I please ask you to enable it for this repo at http://travis-ci.org/)
- Replaces the legacy `distutils` code in `setup.py` with `setuptools`.

Please note that **the tests currently fail on all the attempted combinations of Python and Django.** I have addressed the failures in #3, so that these two stages are easier to review independently.

I realise it's a little odd to add tests for unsupported versions of Django. I'd like to make sure that these old versions are tested in order to provide an upgrade path for legacy projects (which is how I found myself making this PR). Are you happy with that?

### CODE REVIEW

**Comment by meshy** [comment]
You can see the failed test run on travis: https://travis-ci.org/Virtualstock/django-forkit/builds/452810346

**Comment by alb3rto269** [comment]
Hi, thanks for your changes. However, this project is currently unmaintained and instead of accepting the PR we prefer to transfer you the ownership of the project. What do you think?

**Comment by meshy** [comment]
@alb3rto269 thanks for getting back to me. I thought that might be the case. We'll be happy to take this over.

Do you happen to have access to the project on PyPI, or should I look into releasing the project under a new name?

**Comment by meshy** [comment]
FYI, the new fork has been released to PyPI under the name `forkit-django`: https://pypi.org/project/forkit-django/0.10.1/

**Comment by alb3rto269** [comment]
We don't have access to the PyPI. This repository is a fork from https://github.com/ysugiura/django-forkit. You may be interested in that repo instead of this one. If you still want to use our changes feel free to pick them or, as I mentioned, we can transfer you the ownership of this fork.

**Pull request closed without merging**
